gnuboard/gnuboard5

bbs/register_email.php

처음 pull request 해봐서 잘하는 것인지? 또는 정확하게 한 것인지 잘 모르겠습니다.
하지만 조금이라도 도움이 될까 싶어서 한번 해보게 되었습니다.
다른 곳은 전부 <?php 로 되어 있는데 여기만 <? 으로 되어 있어 에러가 났던 적이 있어 pull request 해봅니다.

PHP short_open_tag=0 에러 방지

---

adm/shop_admin/configform.php
adm/shop_admin/configformupdate.php
install/gnuboard5shop.sql
mobile/shop/kcp/global_m_hp_form.php
mobile/shop/kcp/global_m_hp_order.script.php
mobile/shop/orderform.sub.php
mobile/shop/orderformupdate.php
shop/kcp/global_kcp_hp_form.php
shop/orderform.sub.php
shop/orderformupdate.php

타 PG 이용 시 KCP 휴대폰 결제 연동

---

bbs/password_lost.php
bbs/password_reset.php
bbs/register_form_update.php
mobile/skin/member/basic/login.skin.php
mobile/skin/member/basic/password_lost.skin.php
mobile/skin/member/basic/style.css
skin/member/basic/login.skin.php
skin/member/basic/password_lost.skin.php
skin/outlogin/basic/outlogin.skin.1.php
skin/outlogin/shop_basic/outlogin.skin.1.php
skin/outlogin/shop_side/outlogin.skin.1.php
theme/basic/mobile/skin/member/basic/login.skin.php
theme/basic/mobile/skin/member/basic/password_lost.skin.php
theme/basic/mobile/skin/member/basic/style.css
theme/basic/skin/member/basic/login.skin.php
theme/basic/skin/member/basic/password_lost.skin.php
theme/basic/skin/outlogin/basic/outlogin.skin.1.php
theme/basic/skin/outlogin/shop_basic/outlogin.skin.1.php
theme/basic/skin/outlogin/shop_side/outlogin.skin.1.php

- 정보찾기를 ID/PW 찾기 혹은 아이디/비밀번호 찾기로 용어 변경하고 현재창에 뜨도록
- 본인인증을 이용한 아이디/비밀번호 재설정 페이지(only url) 추가함

통합인증 기초 작업

---

adm/config_form.php
bbs/register_form.php
css/default.css
css/mobile.css
mobile/skin/member/basic/password_lost.skin.php
mobile/skin/member/basic/password_reset.skin.php
mobile/skin/member/basic/register.skin.php
mobile/skin/member/basic/register_form.skin.php
mobile/skin/member/basic/style.css
mobile/skin/social/social_register_member.skin.php
skin/member/basic/password_lost.skin.php
skin/member/basic/password_reset.skin.php
skin/member/basic/register.skin.php
skin/member/basic/register_form.skin.php
skin/member/basic/style.css
theme/basic/css/default.css
theme/basic/css/mobile.css
theme/basic/mobile/skin/member/basic/password_lost.skin.php
theme/basic/mobile/skin/member/basic/password_reset.skin.php
theme/basic/mobile/skin/member/basic/register.skin.php
theme/basic/mobile/skin/member/basic/register_form.skin.php
theme/basic/mobile/skin/member/basic/style.css
theme/basic/skin/member/basic/password_lost.skin.php
theme/basic/skin/member/basic/password_reset.skin.php
theme/basic/skin/member/basic/register.skin.php
theme/basic/skin/member/basic/register_form.skin.php
theme/basic/skin/member/basic/style.css

- 통합인증 : 프론트 2차 작업
- 회원: #91 회원가입 페이지 개인정보처리방침 > 개인정보 수집 및 이용으로 문구 변경

통합인증 프론트 2차 작업, #91 개인정보처리방침 문구 변경

---

mobile/skin/member/basic/register_cert_reset.skin.php
mobile/skin/member/basic/register_form.skin.php
mobile/skin/member/basic/style.css
mobile/skin/social/social_register_member.skin.php
mobile/skin/social/style.css
skin/member/basic/register_cert_reset.skin.php
skin/member/basic/register_form.skin.php
skin/member/basic/style.css
skin/social/social_register_member.skin.php
theme/basic/mobile/skin/member/basic/register_cert_reset.skin.php
theme/basic/mobile/skin/member/basic/register_form.skin.php
theme/basic/mobile/skin/member/basic/style.css
theme/basic/skin/member/basic/register_cert_reset.skin.php
theme/basic/skin/member/basic/register_form.skin.php
theme/basic/skin/member/basic/style.css

- 통합인증 : 모바일 공통 스타일 재지정
- 통합인증 : 버튼 중복 id 제거

통합인증 모바일 스타일 추가

---

plugin/social/register_member_update.php

소셜 회원가입 : 누락된 조건 추가

---

mobile/skin/member/basic/register_cert_reset.skin.php
mobile/skin/member/basic/style.css
skin/member/basic/register_cert_reset.skin.php
skin/member/basic/style.css
theme/basic/mobile/skin/member/basic/register_cert_reset.skin.php
theme/basic/mobile/skin/member/basic/style.css
theme/basic/skin/member/basic/register_cert_reset.skin.php
theme/basic/skin/member/basic/style.css

register_cert_reset.php 및 style.css 파일 내 id/class 변경
일부 주석 제거

통합인증 : 기존 회원 본인인증 페이지 id/class명 변경, 주석 제거

---

bbs/register_form.php

회원가입 : 본인인증을 사용하는지 체크하는 조건 추가

---

mobile/skin/member/basic/member_cert_refresh.skin.php
mobile/skin/member/basic/password_reset.skin.php
skin/member/basic/member_cert_refresh.skin.php
skin/member/basic/password_reset.skin.php
theme/basic/mobile/skin/member/basic/member_cert_refresh.skin.php
theme/basic/mobile/skin/member/basic/password_reset.skin.php
theme/basic/skin/member/basic/member_cert_refresh.skin.php
theme/basic/skin/member/basic/password_reset.skin.php

통합인증 : 기존 회원 본인인증 페이지 알림 문구 변경
통합인증 : 비밀번호 재설정 페이지 알림 문구 변경

통합인증 관련 알림 문구 변경

---

plugin/kcpcert/kcpcert_result.php
plugin/kgcert/kg_result.php
plugin/lgxpay/AuthOnlyRes.php
plugin/okname/hpcert2.php
plugin/okname/ipin2.php

본인확인 : submit form name 변경

---

plugin/kgcert/kg_request.php

통합인증 : 특정사용자 구분코드 해제

---

mobile/skin/member/basic/register_form.skin.php
mobile/skin/social/social_register_member.skin.php
skin/member/basic/register_form.skin.php
skin/social/social_register_member.skin.php
theme/basic/mobile/skin/member/basic/register_form.skin.php
theme/basic/skin/member/basic/register_form.skin.php

통합인증 : 인증 안내 출력 조건 추가

---

adm/config_form.php

- 통합인증 : 본인확인 사용 시에만 아이디/비밀번호 찾기에 이용할 수 있도록 수정

통합인증 : 본인확인 사용 시에만 아이디/비밀번호 찾기에 이용할 수 있도록 수정

---

bbs/qaview.php
bbs/qawrite.php
mobile/skin/qa/basic/write.skin.php
skin/qa/basic/write.skin.php
theme/basic/mobile/skin/qa/basic/write.skin.php
theme/basic/skin/qa/basic/write.skin.php

https://github.com/gnuboard/gnuboard5/issues/101 이슈 처리 관련

1:1 문의 파일 첨부 오류, 작은별님 문의 #101

---

mobile/skin/member/basic/register_form.skin.php
mobile/skin/social/social_register_member.skin.php
skin/member/basic/register_form.skin.php
skin/social/social_register_member.skin.php
theme/basic/mobile/skin/member/basic/register_form.skin.php
theme/basic/skin/member/basic/register_form.skin.php

회원가입 : 스킨별 인증 안내 출력 수정사항 반영

---

bbs/member_cert_refresh_update.php

본인인증갱신 : 갱신 쿼리 오류 수정

---

adm/shop_admin/itemform.php

관리자 : #122 쇼핑몰관리 > 상품관리

---

js/certify.js
mobile/skin/member/basic/member_cert_refresh.skin.php
plugin/inicert/ini_result.php

통합인증 : 브라우저로 접근한 모바일에서도 정상적으로 작동하게끔 스크립트 수정

---

mobile/skin/member/basic/member_cert_refresh.skin.php
mobile/skin/member/basic/style.css
skin/member/basic/member_cert_refresh.skin.php
skin/member/basic/style.css
theme/basic/mobile/skin/member/basic/member_cert_refresh.skin.php
theme/basic/mobile/skin/member/basic/style.css
theme/basic/skin/member/basic/member_cert_refresh.skin.php
theme/basic/skin/member/basic/style.css

통합인증 : 추가 개인정보처리방침 안내에 필수 표시 추가, 체크박스 색상 변경

통합인증 : 추가 개인정보처리방침 안내에 필수 표시 추가, 체크박스 색상 변경

---

mobile/skin/member/basic/member_cert_refresh.skin.php
mobile/skin/member/basic/password_lost.skin.php
mobile/skin/member/basic/register_form.skin.php
mobile/skin/member/basic/style.css
skin/member/basic/member_cert_refresh.skin.php
skin/member/basic/password_lost.skin.php
skin/member/basic/style.css
theme/basic/mobile/skin/member/basic/member_cert_refresh.skin.php
theme/basic/mobile/skin/member/basic/password_lost.skin.php
theme/basic/mobile/skin/member/basic/register_form.skin.php
theme/basic/mobile/skin/member/basic/style.css
theme/basic/skin/member/basic/member_cert_refresh.skin.php
theme/basic/skin/member/basic/password_lost.skin.php
theme/basic/skin/member/basic/style.css

회원정보찾기/추가본인인증 페이지 버튼 스타일 변경
모바일 회원가입 - placeholder 문구 변경

Inicert 프론트 변경사항

---

bbs/board.php
bbs/member_cert_refresh_update.php
bbs/member_leave.php
bbs/register_form_update.php
bbs/write.php
lib/common.lib.php
lib/shop.lib.php
mobile/skin/member/basic/password_reset.skin.php
plugin/social/register_member_update.php
skin/member/basic/password_reset.skin.php
theme/basic/mobile/skin/member/basic/password_reset.skin.php
theme/basic/skin/member/basic/password_reset.skin.php

- 비밀번호 찾기 경고 문구 수정
- 회원 직접 탈퇴 시 인증내역 삭제
- 본인인증 갱신 시 이전페이지로 이동하게 수정
- 본인인증 내역 기록 조건 수정

통합인증 : hot-fix

---

adm/shop_admin/price.php

다음 쇼핑하우 URL 수정

---

mobile/shop/mypage.php
mobile/shop/orderinquiry.sub.php
mobile/shop/orderinquiryview.php
mobile/shop/wishlist.php

일부 모바일 페이지에서 모바일 테마 경로가 아닌 PC 테마 경로가 지정되어있는지 체크하는 오류가 있습니다

일부 모바일 페이지에서 테마 파일 체크 오류 수정

---

css/default.css
css/default_shop.css
theme/basic/css/default.css
theme/basic/css/default_shop.css

#155 버튼 스타일 변경

---

shop/price/google_feed.php

구글 판매자센터 피드

---

js/shop.js
skin/latest/basic/style.css
theme/basic/skin/latest/basic/style.css

작은별 님 제보 반영
- https://sir.kr/cm_bug/11208
- https://sir.kr/cm_bug/11213

UI 수정사항 반영

---

common.php

1. HTTP_X_FORWARDED_PROTO 비교 조건 추가
2. 조건문 줄바꿈 처리

Fix gnuboard/gnuboard5#200 HTTP_X_FORWARDED_PROTO 조건 추가

---

lib/common.lib.php

출력 버퍼를 반환하기 전 출력 컨텐츠를 변경할 수 있도록 Hook 추가
add_stylesheet, add_javascript, html_process_add_meta 등을 활용할 수 있으나,
특정 위치에 컨텐츠를 추가하거나 컨텐츠 변경 등의 동작을 처리할 수 있도록 Hook 추가를 반영해주세요.

html_process->run()에 Replace Hook 추가

---

lib/common.lib.php

`alert()`, 'alert_close()` 함수와 마찬가지로 goto_url 함수에도 이벤트를 추가합니다.
alert, alert_close 함수의 이벤트를 이용해 JSON 응답으로 변경하는 등의 처리나 프로세스가 중단되었음을 확인할 수 있는데 goto_url은 register_shutdown으로도 잡히지가 않습니다.
페이지가 리다이렉트 되었음을 확인하기 위해 goto_url 함수에 Hook 추가를 반영해주시기 바랍니다.

goto_url 함수에 Event Hook 추가

---

lib/common.lib.php

get_microtime 함수 개선

---

plugin/editor/cheditor5/imageUpload/upload.php

`get_editor_upload_url` Hook의 세번째 인자에 파일의 추가 정보를 전달.
smarteditor2에서 정의한 것과 동일한 유형으로 데이터를 담음.

CHEditor에서 이미지 업로드시 get_editor_upload_url Hook에 파일의 정보 추가

---

adm/contentformupdate.php
adm/faqformupdate.php
adm/faqmasterformupdate.php
adm/mail_delete.php
adm/mail_update.php
adm/newwinformupdate.php
adm/qa_config_update.php
adm/shop_admin/categoryformupdate.php
adm/shop_admin/itemeventformupdate.php
adm/shop_admin/itemqaformupdate.php
adm/shop_admin/itemqalistupdate.php
adm/shop_admin/itemuseformupdate.php
adm/shop_admin/itemuselistupdate.php
shop/itemqaformupdate.php
shop/itemuseformupdate.php

관리페이지, 영카트 질문/사용후기 등에서 설정 및 항목 추가/변경/삭제 등의 처리 후 이벤트 Hook을 추가했습니다.
DHTML 에디터로 작성되는 곳의 이벤트 수신이 필요하여 추가했습니다.

관리자 페이지 및 일부 데이터 업데이트 시 Event hook 추가

---

css/default_shop.css
css/mobile_shop.css
mobile/skin/member/basic/login.skin.php
mobile/skin/member/basic/style.css
plugin/editor/smarteditor2/photo_uploader/popup/php/JSON.php
plugin/lgxpay/lgdacom/JSON.php
shop/inicis/libs/JSON.php
theme/basic/css/default_shop.css
theme/basic/css/mobile_shop.css
theme/basic/mobile/skin/member/basic/style.css
theme/basic/skin/member/basic/style.css

- 정확한 z-index 포맷을 위해 `'z-index: -1px'`를 `'z-index: -1'`로 수정.
- 올바른 글꼴 두께를 위해 `'font-size:bold;'`를 `'font-weight:bold;'`로 대체.
- 불필요한 닫는 괄호를 제거하여 box-shadow 선언을 간소화.
- 중복된 빈 색상 선언을 제거.
- `.btn_submit`와 `#mb_login_notmb p` 규칙에서 누락된 CSS 속성 값을 수정.
- 중괄호 `{}`를 대괄호 `[]`로 대체하여 권장되는 PHP 구문에 맞춤.
@maycactus-FOSS
- Rectified `'z-index: -1px'` to `'z-index: -1'` for accurate z-index formatting.
- Substituted `'font-size:bold;'` with `'font-weight:bold;'` for correct font weight.
- Streamlined box-shadow declarations by removing unnecessary closing parentheses.
- Eliminated redundant empty color declarations.
- Corrected missing CSS property values in `.btn_submit` and `#mb_login_notmb p` rules.
- Replaced curly braces `{}` with square brackets `[]` to align with recommended PHP syntax.
@maycactus-FOSS

코드 일관성, 가독성 향상 및 버그 수정

---

lib/common.lib.php

`delete_cache_latest()` 함수에 `delete_cache_latest` Hook 추가

`delete_cache_latest` Hook 추가

---

adm/board_copy_update.php
bbs/write_update.php
lib/Cache/obj.class.php
lib/common.lib.php

불필요한 주석을 제거했습니다.
board_copy_update.php 파일의 주석은 서브쿼리를 잘못 사용한 코드가 작동하지 않았던 문제에 대한 주석으로 이제는 필요없는 주석입니다.
나머지는 제 계정이 언급된 주석의 삭제입니다.

불필요한 주석 제거

---

adm/index.php

- adm_index_addtional_content_before
- adm_index_addtional_content_after
`/adm/index.php` 파일 상단과 하단에 컨텐츠를 추가할 수 있는 Replace Hook을 추가했습니다.
```php
add_replace('adm_index_addtional_content_before', function ($content = '', $is_admin, $auth, $member) {
// 권한 체크
if (auth_check_menu($auth, '200100', 'r', true)) {
// ...
}
return $content;
});
```

adm/index.php 페이지에 컨텐츠를 삽입할 수 있는 Hook 추가 

---

plugin/htmlpurifier/extend.video.php

`<img class="Iframevideo">` 태그 사용하여 youtube, facebook, vimeo 위장 도메인에 대한 문제를 보완합니다.

#297 보안취약점 처리 보완
