extend/shop.extend.php

대신택배, 우체국, 한진택배, CVSnet편의점택배, 건영택배의 배송조회 주소를 수정했습니다.
건영택배는 기존 http 대신 https 주소를 사용하도록 수정하였습니다.

fix: 택배사 배송조회 주소 수정

---

config.php
lib/common.lib.php
plugin/debugbar/debugbar.php
plugin/debugbar/style.css

https://github.com/gnuboard/gnuboard5/issues/210 이슈에서 제안했던 개선안을 적용해봤습니다.
이 제안은 아래 사항을 담고있습니다.
- debugbar에 현재 성공한 쿼리 목록만 보여지는 것을 실패한 쿼리와 오류 메시지 표시하여 디버깅 툴에 부합하도록 개선
- debugbar에 쿼리가 실행된 파일 및 함수에 대한 정보 출력 추가
- 디버그 모드(`G5_DEBUG`)를 켜지 않아도 `G5_COLLECT_QUERY` 상수 설정 추가하여 쿼리 목록을 수집할 수 있도록 함
- slow log 및 오류를 수집하여 기록을 남기거나 알림을 제공하는 서드파티 기능 개발 가능성 제공
debugbar에 오류 메시지 출력이 추가와 약간의 스타일 변경이 적용된 화면입니다.
(쿼리 목록은 한 화면에 담기위해 일부 요소를 가렸을 뿐 정상 출력됨)
PHP 5.2에서 동작여부를 확인했습니다.

debugbar 쿼리 오류 표시 추가 및 G5_COLLECT_QUERY 설정 추가

---

lib/common.lib.php

회원 sideview 메뉴를 가져올 때 Replace Hook을 추가합니다.
출력되는 전체 형식은 유지한채로 메뉴 아이템을 배열에 담도록 코드를 수정하고
`member_sideview_items` Hook을 추가해서 전달하고 반환받아 메뉴 항목을 사용자정의할 수 있도록 개선했습니다.
각 항목은 임의의 이름을 가진 연관 배열로 담아 항목이 이미 존재하는지를 확인하거나 변경하기 편하도록 했습니다.
추가로 기존의 각 항목의 링크에 `nofollow` 또는 홈페이지 항목은 `noopener`를 추가해서 우려할 수 있는 보안 문제를 예방하도록 했습니다.
함수 내부에서 static 변수를 이용한 cache를 활용하도록 개선했습니다.
이 Hook 추가로 확장 기능에서 메뉴 항목을 손쉽게 추가할 수 있으니 적용되기를 희망합니다.

회원 sideview 메뉴에 Replace Hook 추가

---

lib/common.lib.php

외부 플러그인에서 구현했던 코드를 옮기다 붙이다보니 실수가 있었습니다.
DB 커넥션 지정의 실수가 있어서 고쳤고 이벤트 리스너에 $source 데이터를 전달하도록 수정했습니다.

#212 PR에서 DB 커넥션 지정 오류 수정 & sql_query_after 이벤트에 누락된 $source 파라메터 추가

---

lib/common.lib.php

`HTMLPurifier`의 설정을 변경하기 위해 코드를 수정해야 하는 불편을 없애기 위해 `html_purifier()`함수에 Event Hook을 추가했습니다.
리스너에서는 첫번째 인자(`$config`)로 `HTMLPurifier_Config` 객체를 받아 설정을 변경할 수 있습니다.
현재 그누보드의 'HTMLPurifier' 설정으로는 필터링된 HTML/CSS 태그나 속성, 스타일 등이 제거 또는 변조되는 것을 이 Hook을 이용해 개선할 수 있습니다.
하나의 예로 https://sir.kr/g5_skin/52457 이 스킨의 CKEditor 5의 `figure` 태그 등이 제거되는 문제를 그누보드의 코드를 직접 수정하지 않고  Hook으로 개선할 수 있습니다.

Hook - HTMLPurifier 설정을 변경할 수 있는 `html_purifier_config` 이벤트 Hook 추가

---

lib/Hook/hook.extends.class.php

Closure는 PHP 5.3에서 추가되었지만 그누보드에서는 현재 Hook 리스너에 클로저를 등록하여 사용할 수가 없습니다.
물론, PHP 5.2에서는 클로저를 사용할 수 없지만 PHP 5.2 환경에서 동작에 영향을 주지 않으면서도 PHP 5.3이상에서 클로저를 사용할 수 있도록 Hook 클래스를 개선했습니다.
기존 동작을 변경하지 않고 `function_exists()` 대신 `is_callable()`로 대체하는 것만으로 개선이 가능합니다.
(`is_callable()` 함수는 PHP 4에서 추가되었습니다.)
PHP 5.2.17 버전과 5.3.29 버전 및 PHP 7 등에서 테스트했습니다.

Hook에 Closure를 리스너로 등록할 수 있도록 개선

---

lib/hook.lib.php

replace hook은 값을 반환해야하므로 항상 최소 1개의 인자를 받아야하지만 기본 값이 0이어서 매번 이를 변경해줘야하는 불편을 해소

add_replace()에서 $args 값을 1로 변경

---

adm/view.php

`$sub_menu`, `$g5['title']` 변수를 생성처리가 `admin_request_handler_*` Event Hook 보다 이후에 실행되어 해당 Hook에서 이를 활용하지 못하는 문제를 해결합니다.

adm/view.php 파일에서 $sub_menu 등 변수 위치를 변경

---

bbs/qadelete.php

답변글의 정보를 잘못 가져오는 문제로 인해 답변글의 첨부파일, 첨부파일의 썸네일, 에디터 이미지의 썸네일을 삭제하지 못하는 문제 고침
답변글을 가져올 때 질의문 조건 누락으로 "답변"이 아닌 "질문"글의 데이터를 잘못 가져와 답변글의 삭제할 데이터를 처리하지 못하는 버그

QA에서 질문글 삭제 시 답변글의 첨부파일 및 썸네일을 삭제하지 못하는 문제 수정

---

bbs/qadelete.php

이는 bcda18cbd5878ee332ca2f223d2ba747e9ca367c 커밋에서 추가된 `qa_delete` Event Hook을 개선하기 위함입니다.
`$tmp_array` 목록은 삭제를 요청한 목록이지만 작성자, 답글 등의 이유로 실제 삭제되지 않을 수 있음.
이로 인해 실제 삭제처리가 완료되지 않은 `qa_id` 목록이 전달될 수 있으므로, 삭제된 것으로 오인하여 처리 시 데이터 손실 문제가 발생할 수 있음
이를 방지하기 위해 호환성을 유지하며 두번째 `$deleted` 인자로 답변글을 포함한 실제로 삭제 처리된 목록만을 넘겨주도록 개선 함.

`qa_delete` Event Hook에서 실제 삭제된 ID 목록을 전달하도록 개선

---

adm/shop_admin/itemcopyupdate.php

영카트에서 상품을 복사한 후에 이벤트 Hook을 추가
Hook Tag: `shop_admin_itemcopy`
전달 인자
* @var string $it_id 원본 아이템 ID
* @var string $new_it_id 복사한 새로운 아이템 ID
* @var array $cp 복사한 아이템 정보
* @var array $copied_item_files 복사한 파일 목록
* @var array $copied_editor_images 복사한 에디터 이미지 목록

영카트 상품 복사 후 `shop_admin_itemcopy` Event Hook 추가

---

bbs/qawrite_update.php

답변 글 작성 시 실행되는 `qawrite_update` Hook에서 삽입된 답변글의 `qa_id`를 전달하도록 개선 함
답변 글이 작성될 때 다섯번째 인자로 `$answer_id`를 전달하며, 그 외에는 `null` 임

1:1문의 답변 시 `qawrite_update` Hook에서 답변 글의 ID를 전달하도록 개선

---

lib/common.lib.php

#247 이슈의 이유로 `sql_password` 함수를 사용하지 않도록 deprecated 표기를 추가했습니다.

sql_password() 함수를 사용하는 것을 권장하지 않음을 표기

---

adm/dbupgrade.php
install/gnuboard5.sql

`admin_menu` Hook 으로 관리자 메뉴를 추가하고 `/adm/view.php` 파일에서 제공하는 Hook 을 사용해 관리페이지의 메뉴와 페이지를 쉽게 추가할 수 있습니다.
https://sir.kr/g5_plugin/8893
이 플러그인에서 이를 활용한 것처럼 메뉴의 ID와 view.php 를 활용할 때 그누보드가 기본적으로 사용하는 숫자 형태를 벗어나 문자열을 지정할 수 있는데 이 길이가 다소 부족합니다.
`{prefix}_auth.au_menu` 컬럼의 길이를 20에서 50자로 늘리도록 개선하여 관리페이지에 메뉴와 페이지를 쉽게 추가할 수 있는 기능의 사용성을 높이는데 도움이 될 것으로 보입니다.
이 제안의 검토해주시고 반영해주시기 바랍니다.

관리권한 설정 시 메뉴명(au_menu)의 길이 제한으로 인한 문제 개선

---

common.php

짧은 주소 '글 이름' 주소로 접근할 때 `$wr_id` 전역변수의 값이 `string` 타입으로  잘못 할당되는 문제를 `int` 타입으로 올바르게 바로 잡습니다

`$wr_id` 전역변수의 값이 잘못된 타입으로 할당되는 문제 고침

---

lib/common.lib.php

변수 이름 오타($lenght)를 $length로 수정하였습니다.

Refactor: str_encrypt 클래스의 변수 이름 수정

---

adm/admin.lib.php
bbs/login_check.php
lib/common.lib.php

이 변경사항은 관리자 계정이 프록시, 무선 접속 환경(와이파이, 셀룰러)에서 IP가 수시로 변경될 수 있는 환경에서 관리페이지 접근 시 수시로 제한이 적용되는 문제를 해결하기 위함입니다.
관리자 계정이 관리페이지에 접근할 때 `ss_mb_key` 세션으로 검증과정을 거치는데 `ss_mb_key` 세션의 값에 IP가 조합되어 사용되므로 IP가 변경되는 환경이라면 관리페이지 접근에 수시로 제한이 적용됩니다.
또한, IP를 가져올 때 사용하는 `get_real_client_ip()` 함수에서 참조하는 `$_SERVER['HTTP_X_FORWARDED_FOR']`는 헤더를 이용해 쉽게 위조가 가능하므로 관리자의 IP가 노출된다면 방어수단으로 사용하기에 적합하지도 않습니다.
`ss_mb_key` 세션의 문자열을 생성할 때 IP를 제거하여 문제를 해결할 수 있습니다.
`ss_mb_key` 값은 회원의 가입일시 + IP + 브라우저 UA 문자열이 조합되어 만들어 집니다.
사실상 회원의 가입일시만으로도 위조가 불가능한 hash를 생성할 수 있으나, 접속 세션의 클라이언트 검증이라는 목적을 유지한다면 가입일시와 UA를 유지하고 IP는 제외할 수 있습니다.
이는 본인이 제보했던 #257 이슈에서 세션 고정취약점 해결 및 HttpOnly로 세션 쿠키가 생성되므로 탈취 가능성을 제거했고 또한, #208 이슈에서도 일반 쿠키의 탈취 가능성도 제거했으므로 IP 등을 제거하기에 문제가 없습니다.
다만, #257 이슈에서 세션고정 취약점을 해결할 때 `SKIP_SESSION_REGENERATE_ID` 상수로 세션고정 취약점이 재현될 수 …

IP 변경으로 인한 관리페이지 접근 시 접속이 제한되는 문제 해결

---

common.php
lib/common.lib.php
mobile/skin/member/basic/login.skin.php

세션 쿠키의 보안을 강화하기 위해 `HttpOnly` 및 `Secure` 속성을 추가했습니다.
- `HttpOnly` 속성은 클라이언트 측 JavaScript가 쿠키에 액세스하는 것을 제한하여 크로스사이트 스크립팅(XSS) 공격의 위험을 줄입니다.
- `Secure` 속성은 쿠키가 안전한(HTTPS) 연결을 통해서만 전송되도록 합니다.

세션 쿠키 보안 강화

---

lib/common.lib.php

[증상]
회원 아이디로 댓글 검색을 하면 내가 작성한 댓글이 포함된 게시글만 조회가 되야하는데
내가 작성한 글(작성한 댓글은 없는)과 내가 댓글 단 글이 모두 조회가 됨
[조치]
내가 댓글 단 글만 조회가 되도록 수정함

게시판에서 회원 아이디로 댓글 검색시 잘못된 결과가 나오는 문제

---

lib/common.lib.php

trim()이 mysql 쿼리에서만 처리되어 hook에 잘못된 회원아이디가 전달될 수 있는 문제.

fix: get_member 함수에서 hook에 잘못된 아이디가 전달될 수 있는 문제 고침

---

mobile/shop/list.php
shop/list.php

Add theme override support for `shop/list.php` and `mobile/shop/list.php` file.
`shop/list.php`와 `mobile/shop/list.php` 파일의 테마 오버라이드 지원.
Includes theme-specific `list.php` if it exists, enabling easier customization without changing core files.
테마 경로에 `list.php`가 있으면 포함하여, 코어를 변경하지 않고 커스터마이징 가능하도록 합니다.

feat: add list.php theme override
